steps:
  - name: 'maven:3.9.5-eclipse-temurin-17'
    entrypoint: mvn
    args: ['package']
    dir: 'app'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/test-architect-449613/test-registry/terst-quarkus', '-f', './src/main/docker/Dockerfile.jvm', '.' ]
    # args: 
    #   - 'build'
    #   - '-f'
    #   - './src/main/docker/Dockerfile.jvm'
    #   - '.'
    dir: 'app'  # Add this line to match the Maven build directory
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/test-architect-449613/test-registry/terst-quarkus']

logsBucket: 'gs://cloud-build-logs12991'
options:
  logging: GCS_ONLY