steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        echo "Current working directory:"
        pwd
        echo "\nDirectory structure:"
        ls -R

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'terst-quarkus', '-f', './app/src/docker/Dockerfile.jvm', '.' ]
    # args: 
    #   - 'build'
    #   - '-f'
    #   - './src/main/docker/Dockerfile.jvm'
    #   - '.'
logsBucket: 'gs://cloud-build-logs12991'
options:
  logging: GCS_ONLY

  # Docker Push
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 
  #          'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage']

  # Entrypoint, timeout and environment variables
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'gcloud'
  #   timeout: 240s
  #   args: ['compute', 'instances', 
  #          'create-with-container', 'my-vm-name',
  #          '--container-image', 
  #          'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage']
  #   env:
  #     - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  #     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'